✨ Bento `amp-gist`
rtCamp/amphtml pull request #15
Opened 2022-01-07 14:27 UTC by deepaklalwani97

2022-01-12 07:15 UTC, AnuragVasanwala approved these changes
LGTM.

2022-01-12 15:56 UTC, ediamin requested changes

2022-01-12 15:56 UTC, ediamin commented on extensions/amp-gist/1.0/test/validator-amp-gist.html
> +    <amp-gist layout="responsive" width="150" height="80"></amp-gist>
No `data-gistid` or `data-file` attribute. Can we duplicate the`validator-amp-gist.html` from v0.1 and use it here?

2022-01-12 15:56 UTC, ediamin commented on extensions/amp-gist/1.0/test/test-amp-gist.js
> +    });
Please add a test case for `data-file`.

2022-01-12 15:56 UTC, ediamin commented on extensions/amp-gist/1.0/storybook/Basic.js
> +};
Please add an example for `file` prop.

2022-01-12 15:56 UTC, ediamin commented on extensions/amp-gist/1.0/storybook/Basic.amp.js
> +  );
Please add an example for data-file attribute.

2022-01-12 15:56 UTC, ediamin commented on extensions/amp-gist/1.0/component.js
> +const DEFAULT_TITLE = 'Github gist';
```suggestion
const DEFAULT_TITLE = 'GitHub Gist';
```

2022-01-13 07:50 UTC, ediamin approved these changes
LGTM. Great work! 👍

2022-02-17 05:08 UTC, closed without merging

2022-02-17 05:10 UTC, AnuragVasanwala commented
This component is merged 🎉